language: java
install: skip

root: required
services:
  - docker
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean buildDockerImage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "PokeapiApp"
  env: "Pokeapiapp-env"
  bucket: "elasticbeanstalk-us-east-2-666098774221"
  bucket_path: "PokeapiApp"
  on:
  branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

