sudo: required
services:
  - docker

script:
  - ./gradlew clean buildDockerImage

after_script:
  - docker run pokeapi

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "jfdelolmo.us-east-2.elasticbeanstalk.com/"
  bucket_path: "pokeapi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"