language: java
install: skip

root: required
services:
  - docker

before_script:
  - chmod +x gradlew        
script: 
  - ./gradlew clean build      
  - docker build -t jfdelolmo/pokeapi . -f Dockerfile.travis  
#  - docker login -u jfdelolmo -p babuchas
  - echo "$DOCKER_HUB_PWD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push jfdelolmo/pokeapi

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "PokeapiApp"
  env: "Pokeapiapp-env"
  bucket: "elasticbeanstalk-us-east-2-666098774221"
  bucket_path: "PokeapiApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

