language: java
install: skip

sudo: required
services:
  - docker
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean buildDockerImage

#after_script:
#  - docker run pokeapi

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "pokeapiapp"
  env: "Pokeapiapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-666098774221"
  bucket_path: "pokeapiapp"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"