spring:
  datasource:
    platform: h2
    url: "jdbc:h2:mem:pokedb"
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /pokedb/console
      settings:
        web-allow-others: true
        trace: false
  main:
    banner-mode: console
  banner:
    location: banner.txt


# custom actuator base path: use root mapping `/` instead of default `/health/`
# override endpoint name for health check: `/health` => `/ping`
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /ping
